name: price_search_app
description: Offline Price Search App with SQLite and CSV Import
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  csv: ^5.1.1
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  intl: ^0.19.0
  flutter_barcode_scanner: ^2.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
